volumes:
  recipe-data:
    external: true
  pg-admin:
    external: true
services:
  fastapi:
    environment:
      DATABASE_URL: postgresql://example_user:secret@db/example
      SIGNING_KEY: ${REACT_APP_SIGNING_KEY}
      WAIT_HOSTS: db:5432
      CORS_HOST: http://localhost:3000
    build:
      context: api
      dockerfile: Dockerfile.dev
    ports:
      - 8000:8000
    volumes:
      - ./api:/app
  ghi:
    image: node:lts-bullseye
    command: /bin/bash run.sh
    working_dir: /app
    volumes:
      - ./ghi:/app
    ports:
      - "3000:3000"
    environment:
      HOST_OS: ${OS}
      NODE_ENV: development
      HOST: "0.0.0.0"
      PUBLIC_URL: http://localhost:3000
      REACT_APP_API_HOST: ${REACT_APP_API_HOST}
      REACT_APP_APP_ID: ${REACT_APP_APP_ID}
      REACT_APP_APP_KEY: ${REACT_APP_APP_KEY}
  db:
    image: postgres:14.5-bullseye
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_USER: example_user
      POSTGRES_DB: example
    ports:
      - "15432:5432"
    volumes:
      - recipe-data:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    volumes:
      - pg-admin:/var/lib/pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: user@user.com
      PGADMIN_DEFAULT_PASSWORD: password
      PGADMIN_DISABLE_POSTFIX: 1
    ports:
      - "5050:80"
